// Auto-generated by deploy.py — do not edit manually
// Strategy: pre-cache app shell; cache audio on demand as it is played.
const CACHE_SHELL = 'flippy-shell-v22.5';
const CACHE_AUDIO = 'flippy-audio-v22.5';
const SHELL_FILES = [
  "index.html",
  "manifest.json",
  "icons/icon-192.png",
  "icons/icon-512.png"
];

// Install: pre-cache the app shell only (fast, ~small)
self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE_SHELL).then(cache => cache.addAll(SHELL_FILES))
  );
  self.skipWaiting();
});

// Activate: delete caches from previous versions
self.addEventListener('activate', e => {
  const keep = [CACHE_SHELL, CACHE_AUDIO];
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => !keep.includes(k)).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

// Fetch: serve from cache if available, else fetch and cache for next time
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  const isAudio = url.pathname.startsWith('/audio/') || url.pathname.endsWith('.mp3');
  const cacheName = isAudio ? CACHE_AUDIO : CACHE_SHELL;

  e.respondWith(
    caches.match(e.request).then(cached => {
      if (cached) return cached;
      return fetch(e.request).then(response => {
        // Only cache successful same-origin responses
        if (response.ok && response.type !== 'opaque') {
          caches.open(cacheName).then(cache => cache.put(e.request, response.clone()));
        }
        return response;
      });
    })
  );
});
